<?php

namespace common\modules\menu\components;

use common\modules\language\models\Language;
use common\modules\menu\assets\MenuAdminAsset;
use common\modules\menu\models\MenuItems;
use common\modules\settings\models\Settings;
use Yii;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

class MenuAdmin extends MenuRender
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        MenuAdminAsset::register(Yii::$app->view);
    }

    public function beforeRenderMenu()
    {
        echo '<ol class="menu-admin">';
    }

    public function afterRenderMenu()
    {
        echo '</ol>';
    }

    public function beginRenderItem()
    {
        echo '<li menuitem-id="' . $this->item->menu_item_id . '">';
        echo "<div class='menu-item'>";
        echo '<div  class="menu-item-title"> ';
        echo $this->item->title[Yii::$app->language];
        echo "</div>";
        echo '<div  class="menu-item-right-block"> ';
        echo '<span class="dripicons-chevron-down glyphicon glyphicon-collapse-down menu-item-get-settings"></span>';
        echo "</div>";
        echo '</div>';
        $this->menuItemSetting();
        echo "<ol>";

    }

    private function menuItemSetting()
    {
        $model = MenuItems::findOne($this->item->menu_item_id);
        $langs = Language::find()->active()->all();
        echo '<div  class="menu-item-settings card shadow" menuitem-id="' . $this->item->menu_item_id . '"> ';
        $form = ActiveForm::begin([
            'id' => 'menu-item-form',
            'options' => ['data-pjax' => true, ['enctype' => 'multipart/form-data']]
        ]); ?>
        <div class="panel panel-default">
            <ul class="nav customtab nav-tabs">
                <?php foreach ($langs as $lang): ?>
                    <li class="nav-item">
                        <a class="nav-link <?= ($lang->code == Yii::$app->language) ? 'active' : '' ?>" href="#slanguage<?= $model->menu_item_id ?>-<?= $lang->code ?>" data-toggle="tab"><?= mb_strtoupper($lang->code) ?></a>
                    </li>
                <?php endforeach; ?>
            </ul>
            <div class="tab-content" style="margin: 0">
                <?php
                foreach ($langs as $lang): ?>
                    <div class="tab-pane fade <?= ($lang->code == Yii::$app->language) ? 'active show' : '' ?>" style="opacity: 1" id="slanguage<?= $model->menu_item_id ?>-<?= $lang->code ?>">
                        <div class="panel panel-default">
                            <div class="panel-wrapper">
                                <div class="panel-body">
                                    <?= $form->field($model, 'title[' . $lang->code . ']')->textInput() ?>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
        <?php
        echo $form->field($model, 'url');
        echo $form->field($model, 'icon');
        echo $form->field($model, 'menu_item_id')->hiddenInput()->label(false);
        echo Html::submitButton(Yii::t('app', 'Menu Update'), ['class' => 'btn btn-primary']);
        echo Html::a(Yii::t('app', 'Menu Remove'), '#menuitem', [
            'class' => 'btn btn-danger pull-right',
            'title' => 'delete',
            'data-query' => 'delete',
            'data-query-delete-selector' => 'li[menuitem-id=' . $this->item->menu_item_id . ']',
            'data-query-method' => 'POST',
            'data-query-url' => yii\helpers\Url::to(["/menu/menu/delete-item"]),
            'data-query-confirm' => Yii::t('app', 'Are you sure?'),
            'data-query-params' => 'id=' . $this->item->menu_item_id . '&menuItemDelete=delete'
        ]);
        ActiveForm::end();
        echo "</div>";
    }

    public function endRenderItem()
    {
        echo '</ol></li>';
    }

    public function beginRenderItemChild()
    {
        echo '<li menuitem-id="' . $this->item->menu_item_id . '">';
        echo "<div class='menu-item'>";
        echo '<div  class="menu-item-title"> ';
        echo $this->item->title[Yii::$app->language];
        echo "</div>";
        echo '<div  class="menu-item-right-block"> ';
        echo '<span class="dripicons-chevron-down glyphicon glyphicon-collapse-down menu-item-get-settings"></span>';
        echo "</div>";
        echo '</div>';
        $this->menuItemSetting();
        echo "<ol>";
    }

    public function endRenderItemChild()
    {
        echo '</ol></li>';
    }

    public function beforeRenderItemChilds()
    {
//        echo "<ol>";
    }

    public function afterRenderItemChilds()
    {
//        echo "</ol>";
    }
}
